### ISSUE TITLE
Option to disable Settings

### ISSUE THREAD

**Issue by Holzhaus** [koniu/recoll-webui#34]
To be able to serve a full-text searchable PDF download server, It would nice to have a config file where I can disable the settings page.

**Comment by koniu** [comment]
You can easily hide it by deleting:
        `<a href="settings" tabindex="-1"><input type="button" value="Settings"></a>`
from views/search.tpl

To completely purge this function you need to delete the section starting with `#{{{ settings/set` from webui.py
