### ISSUE TITLE
Preview/Download is absent

### ISSUE THREAD

**Issue by hagfelsh** [koniu/recoll-webui#41]
Hello koniu,

I've installed recoll & the webui on Debian 7 and for the most part, it works right out of the box.  In a previous installation on a different machine, I had the ability to preview or download files via the browser.  Upon mousever, a blue Preview/Download link would would appear next to the search result. 

This newest installation finds that element absent.  Is there something further that needs doing to enable this, or perhaps I've missed a step documented somewhere...?

Thank you for your help,
h

**Comment by medoc92** [comment]
The preview and download functions need a fairly recent Recoll version to work. If your Debian Recoll is older than the one you used on the previous machine, I would recommend trying to install a more recent one. There are Debian packages on the Recoll web site (recoll.org).

**Comment by hagfelsh** [comment]
Marvelous, thank you!  I upgraded to 1.20.x and it's perfect.

**Comment by koniu** [comment]
you just keep beating me to it medoc, nice one!

**Comment by medoc92** [comment]
���������������������� writes:
 >    you just keep beating me to it medoc, nice one!

Yeah, hard work :)
