### ISSUE TITLE
Not finding anything when MIME type is defined in recoll.conf

### ISSUE THREAD

**Issue by Lalarian** [koniu/recoll-webui#44]
Hello!

I'm using webui + recoll in a jail on my FreeNAS server.
I don't need to index file contents, so I enabled 'indexallfilenames' in recoll.conf and i set 'indexedmimetypes' to text/calendar.

Following recoll's documentation this enables recoll to index all filenames, but no contex, besides the content of text/calendar, but that doesn't matter because I have no calendar files.

So this creates an index conatining only file names.
But when I try searching the index with webui. it won't find anything.
Without setting 'indexedmimetypes' it's working fine, but of course also contents of all known filetypes are indexed, thus making the index process lengthy and resource intensive.

I can see, that the indexing by recoll itself seems to be working fine, because directly opening tha xapiandb files shows me all the filenames.
But there has to be a reason, why webui won't show index filenames with no content.

Could you fix this please?

Thank you :)

**Comment by medoc92** [comment]
I just tried your config, and it works for me. 
What recoll version are you using ?
Start the webui in a way where the stderr messages are accessible, there is hopefully someting useful in there.
