### ISSUE TITLE
Indexed Files remain in webui after deleting them on harddisk

### ISSUE THREAD

**Issue by Hardy74** [koniu/recoll-webui#47]
The topdirs config entry points to local folder on my raspberry-pi (jessie). These folder is the mountpoint to my nas.
Ocrmypdf creates searcheable pdf's and stores them to the local folder, which is the mountpoint. A cronjob calls recollindex -s german, everything is fine.
Now i'm going to delete (or rename) a pdf on my nas. A new call to recollindex -s german will not delete (rename) the entry on the webui, only recollindex -z -s german solves the problem. But this takes much time to reindex.

What can i do to solve this problem?

**Comment by medoc92** [comment]
Hi,

recollindex -s german does not perform indexing, it just builds the stemming db for german.

What you need to to is to set the default stemming languages in the configuration file (~/.recoll/recoll.conf), for example for english and german:

    indexstemminglanguages = english german


and then just recollindex, which will actually perform the indexing and delete obsolete document entries.

**Comment by Hardy74** [comment]
Hi,

thanks a lot. That solved this problem.
Now i got the old message after calling recollindex without parameters: :2:../index/indexer.cpp:305:ConfIndexer::createAspellDict: aspell buildDict failed: aspell dictionary creation command failed.
One possible reason might be missing language data files for lang = de

Apperently that has no effect, because everythings looks like working ok!?
I had to create a symbolic link in /usr/lib/ libaspell.so.15 -> /usr/lib/arm-linux-gnueabihf/libaspell.so.15
because of the location of the library you see in the link. Before creating this link, i got the errormessage that the library could not be found.

Furthermore i added to webui-standalone.py the following lines because i found no other solution to get the date in the results view in german.
import locale
locale.setlocale(locale.LC_ALL, '')

**Comment by medoc92** [comment]
What recoll version are you running ? I think that at least the libaspell.so issue is solved in recent versions. The effect of aspell not working is just that spelling approximation won't be used (this only gets triggered when a request has no results, so you may not notice it).

Also, about aspell and Debian, you may find the following useful:
http://www.lesbonscomptes.com/recoll/BUGS.html#aspelljessie

No opinion about the setlocale issue, maybe koniu will have one ...

**Comment by Hardy74** [comment]
I use Recoll 1.17.3 + Xapian 1.2.19 and recoll web ui v1.18.1, not the master, because i got with the master the error 500 message like described in several forums.

**Comment by medoc92** [comment]
The Recoll version explains the libaspell.so issue, and you can fix the dictionary one by following the indications in the link above (if you care about orthographic approximations).

**Comment by Hardy74** [comment]
Ok, i will read it very soon. I'm setting up my own dms at moment, and it is a lot to read and learn about the different tools and their working togehter.
Thanks a lot for the very fast and specific help and hints!
