### ISSUE TITLE
How to open files directly from browser?

### ISSUE THREAD

**Issue by physicsshark** [koniu/recoll-webui#54]
I am able to open the folder location from the recoll webui interface, but I am not able to open the local file.  Instead, the dialog gives me the option to download the file, which isn't what I want.  I've tried this in both Chrome (using the extension) and Firefox (using the user.js) file.  Am I missing something?

**Comment by nabsiddiqui** [comment]
This is happening to me also in Firefox.  With the chrome extension, however, it seems to work.

**Comment by medoc92** [comment]
Have you had a look at the "Opening files via local links" in ther README ? 
https://github.com/koniu/recoll-webui/blob/master/README.rst

**Comment by nabsiddiqui** [comment]
Yeah I did.  I realized that clicking the title was actually sending me to the download link.  I don't seem to have an "Open" link.  Most of my files are pdfs if that matters.  

When I click on the folders location underneath the title , the "folder view" opens correctly.  Is there a way to change the title to be the file name and location?

**Comment by nabsiddiqui** [comment]
I'm on Firefox for what its worth.

**Comment by physicsshark** [comment]
My experience has been the same.

**Comment by medoc92** [comment]
The change is due to this commit:
https://github.com/koniu/recoll-webui/commit/95e93e4db2ff23d43a896c51d2a2c6a2f9766e09

I'm not too sure why the possibility to open a file was removed, esp. because the author seems to have missed the fact that paths could be translated.

You can restore the old behaviour by changing:

     <div class="search-result-title" id="r{{d['sha']}}" title="{{d['abstract']}}">
      <a href="download/{{number-1}}?{{query_string}}">{{d['label']}}</a>
      </div>

Into:

    <div class="search-result-title" id="r{{d['sha']}}" title="{{d['abstract']}}"><a href="{{url}}">{{d['label']}}</a></div> 

Koniu does not seem to be around, so I'm not too sure what good reason for this to have been changed without making it a setting. Maybe no browser actually supports this anymore ?

**Comment by koniu** [comment]
The 'Open' link is now restored and you can select the default action (when clicking title) in Settings. Tested on Firefox using the method described in the README. If the workarounds changed for other browsers please let me know or, better yet, make a pull request :)

**Comment by nabsiddiqui** [comment]
Thanks works great in Firefox.  I didn't want to start another issue for this but is there a way to display the full filename in the results page like recoll does by default?

**Comment by koniu** [comment]
> is there a way to display the full filename with location in the results page

There's currently no way to configure search output (see #25 ) but you can change `views/result.tpl` to your liking. For example, to replace the link to the file's directory with its full (local) path, change:
`        <a href="{{os.path.dirname(url)}}">{{urllabel}}</a>`
to
`        <a href="{{url)}}">{{url}}</a>`

**Comment by nabsiddiqui** [comment]
That would probably work for my purposes, but unfortunately I get a syntax error with the substitution you provided.

**Comment by medoc92** [comment]
Nabeel Siddiqui writes:
 > That would probably work for my purposes, but unfortunately I get a syntax
 > error with the substitution you provided.
 > 
Typo, there is an excess additional parenthesis leftover from editing the
previous line:


    <a href="{{url)}}">{{url}}</a>

Should be

    <a href="{{url}}">{{url}}</a>

**Comment by nabsiddiqui** [comment]
Thank you works great!!!
