### ISSUE TITLE
hide web interface options

### ISSUE THREAD

**Issue by rafaelrdealmeida** [koniu/recoll-webui#58]
Hello, I'm using recollWebUI and would like to know how to lock or hide the "settings" and "Dates" button of the web interface. I'm starting programming.

best regards!

**Comment by koniu** [comment]
LIke with many other UI modifications you need to edit the relevant template. In this case you want to delete [views/search.tpl:12](https://github.com/koniu/recoll-webui/blob/master/views/search.tpl#L12) and [views/search.tpl:27-28](https://github.com/koniu/recoll-webui/blob/master/views/search.tpl#L27-L28). You can also &lt;!-- comment  --&gt; them out.

**Comment by rafaelrdealmeida** [comment]
thank you! It worked right here!
