### ISSUE TITLE
Option to hide Subdirectories in „Folder“-Filter

### ISSUE THREAD

**Issue by alexg-k** [koniu/recoll-webui#59]
Thank you for this neat little tool!

I have two top directories and many many subfolders within. This results in a lot of scrolling to filter for one of the two top directories.

I would appreciate an option to only show the top directories in the filter dropdown.

**Comment by koniu** [comment]
Hi Alex, in settings there's an option called "folder depth" which
determines how deep that dropdown lists directories- you want 1 in there.

**Comment by alexg-k** [comment]
Thank you! I needed to set it to 0 to achieve what I wanted.
