### ISSUE TITLE
Python3 port

### ISSUE THREAD

**Issue by viktor-c** [koniu/recoll-webui#64]
I've been using the script for a couple of days in a docker container. I unfortunately have to install python 3. recoll-webui is not working out of the box with it. Tried some fast cheats... but it did not help. 
Maybe you have some time to port it to Python3! Please!
BR
Viktor

**Comment by alexg-k** [comment]
Check out this fork: https://opensourceprojects.eu/p/recollwebui/

**Comment by aldobranti** [comment]
Hi, I just tried that link to opensourceprojects.eu but get a html 500 error, the host opensourceprojects.eu is still there (pings) have the git repositories moved ?

**Comment by viktor-c** [comment]
Found no infos on the website being dead... Maybe try in a couple of days again

**Comment by viktor-c** [comment]
> Hi, I just tried that link to opensourceprojects.eu but get a html 500 error, the host opensourceprojects.eu is still there (pings) have the git repositories moved ?

Try https://framagit.org/medoc92/recollwebui
It got recent updates and works on Python3
