### ISSUE TITLE
Permanent locations settings for all users

### ISSUE THREAD

**Issue by Floppik** [koniu/recoll-webui#78]
How permanent setup this settings for all users?
![image](https://user-images.githubusercontent.com/38560023/88026359-6b7d3500-cb3e-11ea-80a8-1c5477b22e06.png)
If i try open webui from other pc, i see defults settings:
![image](https://user-images.githubusercontent.com/38560023/88026449-92d40200-cb3e-11ea-842c-054074c5f016.png)
I need to setup it permanent, because i can't explain each user in my network how can it must change to open files locally in they browsers

**Comment by koniu** [comment]
Hi, please pull the `config` branch, with this commit https://github.com/koniu/recoll-webui/commit/61d4e57ed682c98c94d97bfcffd8f6e6093d2533, and let me know if it works.

Mind that if any of the users had c hanged anything in the 'Settings' on their clients, they might already have the paths stored in their local cookies (which take precedence). In that case those cookies will need to be cleared for the server override to take effect.

**Comment by Floppik** [comment]
Thanks, it is worked like a charm! You may close this issue
